### ISSUE TITLE
Missing zoneinfo module

### ISSUE THREAD

**Issue by zach-is-my-name** [yankeexe/timezones-cli#9]
`$ tz search "london"` 
```
Traceback (most recent call last):
  File "/home/zmg/.local/bin/tz", line 5, in <module>
    from timezones_cli.main import cli
  File "/home/zmg/.local/lib/python3.8/site-packages/timezones_cli/main.py", line 4, in <module>
    from timezones_cli.commands import add, get, remove, search, select, show, utc
  File "/home/zmg/.local/lib/python3.8/site-packages/timezones_cli/commands/__init__.py", line 6, in <module>
    from timezones_cli.commands.get import get
  File "/home/zmg/.local/lib/python3.8/site-packages/timezones_cli/commands/get.py", line 3, in <module>
    from zoneinfo import ZoneInfo, available_timezones
ModuleNotFoundError: No module named 'zoneinfo'

```

**Comment by yankeexe** [comment]
@zach-is-my-name thank you for highlighting the issue. 
Please update to the latest version for resolution.

```sh
pip install --upgrade timezones-cli
```
